---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-role
  namespace: default
rules:
- apiGroups: [ "batch" ]
  resources: ["jobs"]
  verbs: ["watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-role
subjects:
- kind: ServiceAccount
  name: control-user
  namespace: default