apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: etcd-data
  name: etcd-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
