apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: frontend
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080