#!/bin/bash

set -e

export DOCKER_TAG="${1:-latest}"
export WORKER_COUNT="${WORKER_COUNT:-2}"

# Validate required environment variables
: "${RUSTFS_ACCESS_KEY:?Need to set RUSTFS_ACCESS_KEY}"
: "${RUSTFS_SECRET_KEY:?Need to set RUSTFS_SECRET_KEY}"
# Skip TURNSTILE_SECRET_KEY validation in CI environments
if [ -z "$CI" ]; then
  : "${TURNSTILE_SECRET_KEY:?Need to set TURNSTILE_SECRET_KEY}"
fi

for file_path in k8/*.yaml.tpl; do
    filename="$(basename ${file_path})"
    outname="k8/generated-${filename/%.yaml.tpl/.yaml}"
    rm -f $outname
    echo "# Generated by: WORKERCOUNT=${WORKER_COUNT} bash $(basename $0) $1" >> $outname
    envsubst < "$file_path" >> $outname
done
