apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: squid
  name: squid
spec:
  ports:
    - name: "3128"
      port: 3128
      targetPort: 3128
  selector:
    io.kompose.service: squid
